"""add user role

Revision ID: 133c9c2e0988
Revises: 1f03bd1c7526
Create Date: 2026-10-07 10:45:21.105194

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '133c9c2e0988'
down_revision: Union[str, Sequence[str], None] = '1f03bd1c7526'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('role', sqlmodel.sql.sqltypes.AutoString(length=20), server_default='client', nullable=False))
    op.create_index(op.f('ix_users_role'), 'users', ['role'], unique=False)
    op.create_check_constraint('ck_users_role', 'users', "role IN ('admin', 'provider', 'client')")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('ck_users_role', 'users', type_='check')
    op.drop_index(op.f('ix_users_role'), table_name='users')
    op.drop_column('users', 'role')
    # ### end Alembic commands ###
