"""create bookings table

Revision ID: 2860d61cd40f
Revises: 03ff9541bb69
Create Date: 2026-09-30 07:43:18.656873

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '2860d61cd40f'
down_revision: Union[str, Sequence[str], None] = '03ff9541bb69'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('availability_rules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('day_of_week', sa.Integer(), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=False),
    sa.Column('end_time', sa.Time(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.CheckConstraint('day_of_week BETWEEN 0 AND 6', name='ck_availability_rules_valid_day'),
    sa.CheckConstraint('start_time < end_time', name='ck_availability_rules_valid_time_range'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'day_of_week', 'start_time', 'end_time', name='uq_availability_rules_provider_date_time')
    )
    op.create_table('provider_services',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('provider_id', sa.Integer(), nullable=False),
    sa.Column('service_type_id', sa.Integer(), nullable=False),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('duration_minutes', sa.Integer(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.CheckConstraint('duration_minutes > 0', name='ck_provider_services_duration_positive'),
    sa.CheckConstraint('price > 0', name='ck_provider_services_price_positive'),
    sa.ForeignKeyConstraint(['provider_id'], ['providers.id'], ),
    sa.ForeignKeyConstraint(['service_type_id'], ['service_types.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('provider_id', 'service_type_id', name='uq_provider_services_provider_service_type')
    )
    op.create_index(op.f('ix_provider_services_provider_id'), 'provider_services', ['provider_id'], unique=False)
    op.create_index(op.f('ix_provider_services_service_type_id'), 'provider_services', ['service_type_id'], unique=False)
    op.create_table('bookings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('provider_service_id', sa.Integer(), nullable=False),
    sa.Column('start_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('price_at_booking', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('notes', sqlmodel.sql.sqltypes.AutoString(length=1000), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("status IN ('pending', 'confirmed', 'completed','canceled')", name='ck_bookings_valid_status'),
    sa.CheckConstraint('0 < price_at_booking', name='ck_bookings_price_positive'),
    sa.CheckConstraint('start_at < end_at', name='ck_bookings_valid_time_range'),
    sa.ForeignKeyConstraint(['client_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['provider_service_id'], ['provider_services.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_bookings_client_start', 'bookings', ['client_id', 'start_at'], unique=False)
    op.create_index('ix_bookings_provider_service_start', 'bookings', ['provider_service_id', 'start_at'], unique=False)
    op.drop_constraint(op.f('service_types_category_id_key'), 'service_types', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('service_types_category_id_key'), 'service_types', ['category_id'], postgresql_nulls_not_distinct=False)
    op.drop_index('ix_bookings_provider_service_start', table_name='bookings')
    op.drop_index('ix_bookings_client_start', table_name='bookings')
    op.drop_table('bookings')
    op.drop_index(op.f('ix_provider_services_service_type_id'), table_name='provider_services')
    op.drop_index(op.f('ix_provider_services_provider_id'), table_name='provider_services')
    op.drop_table('provider_services')
    op.drop_table('availability_rules')
    # ### end Alembic commands ###
